### ISSUE TITLE
Unclaiming land & MOTD

### ISSUE THREAD

**Issue by ketchupcoke** [ShepherdJerred/stTowns#2]
At the moment there is currently no way to unclaim land without destroying the town, which can be a problem. Also, would it be possible to add an option to change the "Change your town MOTD with /town set motd" message - I believe it's currently the only non-configurable one.

**Comment by ShepherdJerred** [comment]
Land unclaiming is planned, however the command is a bit complex to create.

The default town MOTD will be configurable in the next release

**Comment by ShepherdJerred** [comment]
Unclaim command is finished. It'll also be added in the next release.

**Comment by ShepherdJerred** [comment]
Latest version includes these features.
