### ISSUE TITLE
"CANNOT FIND PATH" for "/town promote"

### ISSUE THREAD

**Issue by WolfieGaming** [ShepherdJerred/sttowns#5]
When you promote a player in your town with  "/town promote <player>"  it prints to chat; "CANNOT FIND PATH [stTowns]: PLAYER was promoted to an assistant of TOWN IN MESSAGES.YML" (PLAYER and TOWN are replaced with the town and player name), even though the path "messages.towns.promote.townBroadcast" is '&3%player% &7was &apromoted &7to an &3assistant &7of &3%town%'.

**Comment by ShepherdJerred** [comment]
Try deleting your messages.yml and reproduce the error. If it still occurs, send me a console log of the error.

**Comment by WolfieGaming** [comment]
I did what you said and didn't edit the file (messages.yml) at all and I still got the same thing in chat. No errors in console though, it just says that I (the player) entered the command.

**Comment by ShepherdJerred** [comment]
Fixed in the rewrite
